name: sleeplogger
description: Sleep logger

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+14

environment:
#  sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mwwm: ^0.1.3-dev.8
  relation: ^0.0.4-dev.3

  provider: ^5.0.0

  slide_to_act: any

  just_audio: ^0.6.15+1

  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.0
  firebase_crashlytics: ^0.4.0+1
  firebase_storage: ^7.0.0

  wakelock: ^0.2.1+1

  flutter_markdown: ^0.6.1

  font_awesome_flutter: ^9.0.0

  shared_preferences: ^0.5.0

  platform_device_id: ^0.1.3

  path_provider: ^1.6.28
  path: ^1.8.0

  mailer: ^5.0.0

  translit: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
#  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

  assets:
    - res/
    - res/sound/
    - res/launch_icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/launch_icon/launch_icon.png"